---
- hosts: all
  become: yes
  roles:
    - { role: default_packages, tags: ['default_packages'] }
    - { role: nginx_custom, tags: ['nginx_custom'] }
    - { role: nginx_proxy, tags: ['nginx_proxy'], when: "'vm2' in inventory_hostname" } 
